// Generated by CoffeeScript 1.7.1
var greeting, greeting2;

$('p').html($('p').html());

(function() {
  return 'Hello Functions!';
});

console.log((function() {
  return 'Hello World!';
})());

greeting = function(subject) {
  return "hello, " + subject;
};

console.log(greeting('sxf'));

greeting2 = "Hello, " + arguments[0];

console.log(greeting({
  'sxf': 'sxf',
  'abc': 'abc'
}));

console.log((function() {
  return 'Hello World';
})());
